Global:
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_chinese_common_v2.0
  save_epoch_step: 3
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [ 0, 2000 ]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words/ch/word_1.jpg
  # for data or label process
  character_dict_path: ppocr/utils/dict/chinese_cht_dict.txt
  character_type: ch
  max_text_length: 25
  infer_mode: False
  use_space_char: True
  save_res_path: ./output/rec/predicts_chinese_common_v2.0.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
  regularizer:
    name: 'L2'
    factor: 0.00004

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: ResNet
    layers: 34
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 256
  Head:
    name: CTCHead
    fc_decay: 0.00004

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/rec_all/dataset
    label_file_list:
#      - ./train_data/rec_all/label/digit
      - ./train_data/rec_all/label/hand-line
      - ./train_data/rec_all/label/hand-sign
      - ./train_data/rec_all/label/hand-write
      #      - ./train_data/rec_all/label/label_train_ppocr
#      - ./train_data/rec_all/label/line-01
#      - ./train_data/rec_all/label/line-04
#      - ./train_data/rec_all/label/line-05
#      - ./train_data/rec_all/label/line-06
#      - ./train_data/rec_all/label/line-07
#      - ./train_data/rec_all/label/line-08
#      - ./train_data/rec_all/label/line-09
#      - ./train_data/rec_all/label/line-11
#      - ./train_data/rec_all/label/line-13
#      - ./train_data/rec_all/label/line-14
#      - ./train_data/rec_all/label/line-15
#      - ./train_data/rec_all/label/line-16
#      - ./train_data/rec_all/label/line-17
#      - ./train_data/rec_all/label/web-line
#    ratio_list: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ]
    ratio_list: [ 1.0, 1.0, 1.0 ]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug:
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [ 3, 32, 512]
      - KeepKeys:
          keep_keys: [ 'image', 'label', 'length' ] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/rec_all/dataset
    label_file_list:
#      - ./train_data/rec_all/label/label_test_ppocr
      - ./train_data/rec_all/label/line
    ratio_list: [ 1.0]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [ 3, 32, 512 ]
      - KeepKeys:
          keep_keys: [ 'image', 'label', 'length' ] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 8
